export const MOVIE_SEARCH_REQUEST = "MOVIE_SEARCH_REQUEST";
export const MOVIE_SEARCH_SUCCESS = "MOVIE_SEARCH_SUCCESS";
export const MOVIE_DETAILS = "MOVIE_DETAILS";
export const MOVIE_SEARCH_FAILED = "MOVIE_SEARCH_FAILED";
export const SEARCH_NOT_FOUND = "SEARCH_NOT_FOUND";

export const MOVIE_CASTS = "MOVIE_CASTS";
export const MOVIE_TRAILER = "MOVIE_TRAILER";
